error exit if mkisofs not found

diff --git a/src/cdtv-qdtitle b/src/cdtv-qdtitle
--- a/src/cdtv-qdtitle
+++ b/src/cdtv-qdtitle
@@ -31,6 +31,7 @@
 
 # - Check md5 hash of CDTV.tm to make sure it's contents is correct
 # - Add more URLs of CDTV.tm sources
+# - Check for mkisofs in path
 
 
 ISO="${2}"
@@ -72,7 +73,7 @@ function source_tm {
 }
 
 
-# Check inputs
+# Pre-flight checks
 
 if [ -z "${STAGINGDIR}" ]; then
   echo "ERROR: Please provide the path to the directory you want create a CDTV title of as the first paramater."
@@ -81,6 +82,12 @@ fi
 
 if [ -z "${ISO}" ]; then
   ISO="CDTVtitle.iso"
+fi
+
+which mkisofs
+if [ $? -ne 0 ]; then
+  echo "ERROR: Could not find mkisofs. Please make sure it is installed and found through your PATH env."
+  exit 1
 fi
 
 
